import enum

class CxlMailboxReturnCodes(enum.IntEnum):
    """
    CXL spec pg. 655-656 Table 8-208 
    """
    SUCCESS = 0x00
    BACKGROUND_COMMAND_STARTED = 0x01
    INVALID_INPUT = 0x02
    UNSUPPORTED = 0x03
    INTERNAL_ERROR = 0x04
    RETRY_REQUIRED = 0x05
    BUSY = 0x06
    MEDIA_DISABLED = 0x07
    FW_TRANSFER_IN_PROGRESS = 0x08
    FW_TRANSFER_OUT_OF_ORDER = 0x09
    FW_AUTHENTICATION_FAILED = 0x0A
    INVALID_SLOT = 0x0B
    ACTIVATION_FAILED_FW_ROLLED_BACK = 0x0C
    ACTIVATION_FAILED_COLD_RESET_REQUIRED = 0x0D
    INVALID_HANDLE = 0x0E
    INVALID_PHYSICAL_ADDRESS = 0x0F
    INJECT_POISON_LIMIT_REACHED = 0x10
    PERMANENT_MEDIA_FAILURE = 0x11
    ABORTED = 0x12
    INVALID_SECURITY_STATE = 0x13
    INCORRECT_PASSPHRASE = 0x14
    UNSUPPORTED_MAILBOX = 0x15
    INVALID_PAYLOAD_LENGTH = 0x16
    INVALID_LOG = 0x17
    INTERRUPTED = 0x18
    UNSUPPORTED_FEATURE_VERSION = 0x19
    UNSUPPORTED_FEATURE_SELECTION_VALUE = 0x1A
    FEATURE_TRANSFER_IN_PROGRESS = 0x1B
    FEATURE_TRANSFER_OUT_OF_ORDER = 0x1C
    RESOURCES_EXHAUSTED = 0x1D
    INVALID_EXTENT_LIST = 0x1E
    